version: "3"

networks:
  hlc_network: {
    driver: "bridge"
  } 
services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - hlc_network
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
  postgres:
    image: postgres:15
    restart: always
    ports:
      - ${DB_PORT}:5432
    networks:
      - hlc_network
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
volumes:
  db_data:
  node_modules: